# Generated by Django 4.2 on 2025-11-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_creado_por_alter_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20),
        ),
    ]
