# Generated by Django 4.2 on 2025-11-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_referencia_pago_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=10),
        ),
    ]
