# Generated by Django 4.2 on 2025-11-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_factura_venta'),
        ('ventas', '0005_alter_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_rel', to='facturas.factura'),
        ),
    ]
