# Generated by Django 4.2 on 2025-11-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_venta_estado'),
        ('facturas', '0002_factura_cambio_entregado_factura_efectivo_recibido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_sipv', to='ventas.venta'),
        ),
    ]
