# Generated by Django 4.2 on 2025-10-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0002_categoria_actualizado_producto_actualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('AJUSTE_POS', 'AJUSTE_POS'), ('AJUSTE_NEG', 'AJUSTE_NEG')], max_length=12)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=30)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='maestros.producto')),
            ],
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'creado'], name='inventario__product_ca53de_idx'),
        ),
    ]
