# Generated by Django 4.2 on 2025-10-24 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_categoria_actualizado_producto_actualizado_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('actualizado', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='existencia', to='maestros.producto')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'db_table': 'inventario_existencia',
            },
        ),
    ]
