# Generated by Django 4.2 on 2025-10-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFiscalSAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cai', models.CharField(max_length=40)),
                ('rango_inicio', models.CharField(max_length=19)),
                ('rango_fin', models.CharField(max_length=19)),
                ('correlativo_actual', models.IntegerField(default=0)),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=19, unique=True)),
                ('isv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('control_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sar.controlfiscalsar')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ventas.venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
