# Generated by Django 4.2 on 2025-12-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='control_fiscal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='venta',
        ),
        migrations.DeleteModel(
            name='ControlFiscalSAR',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
