# Generated by Django 4.2 on 2025-10-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_apertura', models.DateTimeField()),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('abierta', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
