# Generated by Django 4.2 on 2025-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=4),
        ),
    ]
