# Generated by Django 4.2 on 2025-11-01 07:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_categoria_actualizado_producto_actualizado_and_more'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RenameField(
            model_name='compradetalle',
            old_name='costo_unit',
            new_name='costo_unitario',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='recibido',
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='isv_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compra',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='maestros.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_detalle', to='maestros.producto'),
        ),
    ]
