# Generated by Django 4.2 on 2025-11-01 07:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_categoria_actualizado_producto_actualizado_and_more'),
        ('compras', '0002_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compradetalle',
            options={'verbose_name': 'Detalle de compra', 'verbose_name_plural': 'Detalles de compra'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='compradetalle',
            name='isv_porcentaje',
        ),
        migrations.AddField(
            model_name='compra',
            name='procesada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='tasa_impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.producto'),
        ),
    ]
