# Generated by Django 4.2 on 2025-11-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_options_compradetalle_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
