# Generated by Django 4.2 on 2025-11-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_producto_imagen'),
        ('compras', '0006_compra_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='maestros.proveedor'),
        ),
    ]
