# Generated by Django 4.2 on 2025-10-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(max_length=50)),
                ('objeto', models.CharField(max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
